"""continue

Revision ID: 7cd9ecea11e3
Revises: 2d26974a57ff
Create Date: 2026-03-01 23:55:35.428506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd9ecea11e3'
down_revision: Union[str, Sequence[str], None] = '2d26974a57ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorie_pin',
    sa.Column('Id_categorie', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_Categorie', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id_categorie')
    )
    op.create_index(op.f('ix_Categorie_pin_label_Categorie'), 'Categorie_pin', ['label_Categorie'], unique=False)
    op.create_table('SubCategorie_pin',
    sa.Column('Id_Subcategorie', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_SubCategorie', sa.String(length=255), nullable=False),
    sa.Column('Id_categorie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_categorie'], ['Categorie_pin.Id_categorie'], ),
    sa.PrimaryKeyConstraint('Id_Subcategorie')
    )
    op.create_index(op.f('ix_SubCategorie_pin_label_SubCategorie'), 'SubCategorie_pin', ['label_SubCategorie'], unique=False)
    op.create_table('Pins_Images',
    sa.Column('Pin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('Pin_url', sa.Text(), nullable=False),
    sa.Column('Pin_local_path', sa.Text(), nullable=False),
    sa.Column('Pin_source', sa.String(length=255), nullable=False),
    sa.Column('Jobs', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('Pin_categorie', sa.Integer(), nullable=False),
    sa.Column('Pin_SubCategorie', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['Pin_SubCategorie'], ['SubCategorie_pin.Id_Subcategorie'], ),
    sa.ForeignKeyConstraint(['Pin_categorie'], ['Categorie_pin.Id_categorie'], ),
    sa.PrimaryKeyConstraint('Pin_id')
    )
    op.create_index(op.f('ix_Pins_Images_Pin_source'), 'Pins_Images', ['Pin_source'], unique=False)
    op.create_index(op.f('ix_Pins_Images_article_id'), 'Pins_Images', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pins_Images_article_id'), table_name='Pins_Images')
    op.drop_index(op.f('ix_Pins_Images_Pin_source'), table_name='Pins_Images')
    op.drop_table('Pins_Images')
    op.drop_index(op.f('ix_SubCategorie_pin_label_SubCategorie'), table_name='SubCategorie_pin')
    op.drop_table('SubCategorie_pin')
    op.drop_index(op.f('ix_Categorie_pin_label_Categorie'), table_name='Categorie_pin')
    op.drop_table('Categorie_pin')
    # ### end Alembic commands ###
