"""empty message

Revision ID: be46a60fe597
Revises: f406e51feb56
Create Date: 2026-03-03 08:34:25.221343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be46a60fe597'
down_revision: Union[str, Sequence[str], None] = 'f406e51feb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Pins_Images', 'Pin_categorie',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Pins_Images', 'Pin_SubCategorie',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('Pins_Images_ibfk_2'), 'Pins_Images', type_='foreignkey')
    op.drop_constraint(op.f('Pins_Images_ibfk_1'), 'Pins_Images', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('Pins_Images_ibfk_1'), 'Pins_Images', 'SubCategorie_pin', ['Pin_SubCategorie'], ['Id_Subcategorie'])
    op.create_foreign_key(op.f('Pins_Images_ibfk_2'), 'Pins_Images', 'Categorie_pin', ['Pin_categorie'], ['Id_categorie'])
    op.alter_column('Pins_Images', 'Pin_SubCategorie',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('Pins_Images', 'Pin_categorie',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
