"""third_modif

Revision ID: f406e51feb56
Revises: 7cd9ecea11e3
Create Date: 2026-03-02 02:39:58.651701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f406e51feb56'
down_revision: Union[str, Sequence[str], None] = '7cd9ecea11e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pins_Images', sa.Column('Pin_title', sa.String(length=255), nullable=False))
    op.add_column('Pins_Images', sa.Column('Pin_keywords', sa.Text(), nullable=False))
    op.add_column('Pins_Images', sa.Column('Pin_Ambiance', sa.Text(), nullable=False))
    op.alter_column('Pins_Images', 'Pin_local_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Pins_Images', 'Pin_local_path',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               nullable=False)
    op.drop_column('Pins_Images', 'Pin_Ambiance')
    op.drop_column('Pins_Images', 'Pin_keywords')
    op.drop_column('Pins_Images', 'Pin_title')
    # ### end Alembic commands ###
